version: "3.7"
services:
  duelbackend:
    build:
      context: ./services/backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./services/backend:/app
    container_name: unitduel-b
  duelfrontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.prod
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 1337:80
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: unitduel-f
#  dueldb:
#    image: mongo
#    ports:
#      - "27017:27017"
#    container_name: unitduel-db