version: "3.8"
services:
  duelbackend:
    build:
    ports:
      - "8080:8080"
    volumes:
      - ./services/backend:/app
    container_name: duelBackend
  duelfrontend:
    build:
    context: .
    dockerfile: ./services/frontend/Dockerfile.prod
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 1337:80
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: unitduel-f
#  dueldb:
#    image: mongo
#    ports:
#      - "27017:27017"
#    container_name: duelDB