# создаём среду
FROM node:14.15.1-alpine
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./package.json ./
COPY ./yarn.lock ./
RUN npm install yarn
RUN yarn 
COPY . ./
RUN yarn build 

# боевая среда
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]